In [10]:
import numpy as np

ngrid=5
ntime=10
D=1.0
dx=1.0
dt  = 0.1

dx_sq = dx * dx
p=np.array(np.zeros(ngrid))
p[ngrid/2]=1.0

D*dt/dx_sq

0.1

In [11]:
p

array([0., 0., 1., 0., 0.])

In [7]:
np.gradient(p)

array([-1. , -0.5,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ])

In [15]:
np.diff(p,n=2,append=p[0],prepend=p[-1])

array([ 0.,  1., -2.,  1.,  0.])

In [13]:
help(np.diff)

Help on function diff in module numpy:

diff(a, n=1, axis=-1, prepend=<no value>, append=<no value>)
    Calculate the n-th discrete difference along the given axis.
    
    The first difference is given by ``out[n] = a[n+1] - a[n]`` along
    the given axis, higher differences are calculated by using `diff`
    recursively.
    
    Parameters
    ----------
    a : array_like
        Input array
    n : int, optional
        The number of times values are differenced. If zero, the input
        is returned as-is.
    axis : int, optional
        The axis along which the difference is taken, default is the
        last axis.
    prepend, append : array_like, optional
        Values to prepend or append to "a" along axis prior to
        performing the difference.  Scalar values are expanded to
        arrays with length 1 in the direction of axis and the shape
        of the input array in along all other axes.  Otherwise the
        dimension and shape must match "a" except along ax